version: '3.7'

services:
  keygen:
    build:
      context: contexts
      dockerfile: ../Dockerfile
    environment:
      - "NAMES=name1:name2"
    volumes:
      - "./save/keys:/keys"
      - "/tmp/ram:/workplace"
    stop_grace_period: 1s
